#pragma once

#include "coms_manager/serial_manager.hpp"
#include "coms_manager/ipmanager.hpp"



/**
 * @mainpage Communication Manager Documentation.
 * @author Tom Shorrock (t.h.shorrock@gmail.com)
 * @date   January, 2011
 * @section purpose_sec Purpose
 * 
 * Provide a cross platform c++ interface to serial and LAN devices
 *
 * This is provided curtosy of the ICR::coms::IPmanager
 * and ICR::coms::serial_manager classes.
 *
 * @section example_sec Example:
@code
#include "coms_manager.hpp"
int
main  (int ac, char **av)
{
  //use the coms namespace
  using namespace ICR::coms;
  
  // Open a LAN connection to port 5025 to the IP address "10.0.0.10"
  IPmanager ip("10.0.0.10", "5025");
  
  //send a command, for example "REMOTE\n" to this device.
  ip.send("REMOTE\n");
  
  //Open a serial connection to a device attached to "COM1" port - with baud rate of 19200, no flow control, no parity and no stop bits and char size 8 (the defaults).
  serial_manager serial("COM1");
  
  //send a command to the serial device
  serial.send("REMOTE\n");

  //The connections automatically close when out of scope.
}
@endcode

\section feature_sec Feature
A swig interface file is provided for this library.
This means that a wrapper to the c++ library is easily created for any of the following languages:
 - AllegroCL
 - C# - Mono
 - C# - MS .NET
 - CFFI
 - CHICKEN
 - CLISP
 - Go language
 - Guile
 - Java
 - Lua
 - MzScheme
 - Ocaml
 - Octave (and Matlab via Octave)
 - Perl
 - PHP
 - Python
 - R
 - Ruby
 - Tcl/Tk



\section dependancies_sec Dependancies.
 This library uses the Boost c++ libraries.  These are already included in the distribution.

\section git_repo_sec Location of the Repository

\section installation_sec Installation

This library is most conveniently installed with bjam (on both Windows and Linux based operating systems).
 - First setup bjam (which can be downloaded from http://www.boost.org/)
 - go to the root directory and type:
  \code bjam --v2 \endcode

@section licence_sec Licence
Since the library uses the Boost c++ libraries, the Boost lisence applies.

\verbatim
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
\endverbatim
*/

  /** @file /include/coms_manager.hpp
 *  @brief The communications header files are specified
 *
 */
